language: php

php:
  - 5.3
  - 5.4

notifications:
  email:
    - daniel.gonzalez@freelancemadrid.es

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - phpunit
